version: '3.1'

services:
  db:
    image: mariadb:10.6
    ports:
      - 3306:3306
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123

  phpmyadmin:
    image: phpmyadmin
    # restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1